import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Navbar from "./components/Navbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <div className="fixed inset-0 pointer-events-none z-60 border-15 border-white"></div>
        <div className="fixed inset-0 z-0 p-5 bg-black"></div>
        <Navbar />
        <main className="relative z-10 min-h-screen w-full flex items-center justify-center px-10">
          <div className="w-full max-w-4xl">{children}</div>
        </main>
      </body>
    </html>
  )
}
